codecov:
  token: "1ebe6d80-9876-4035-86a7-3999461e573b"
  bot: "codecov-io"
  ci:
    - "github.com"
  strict_yaml_branch: "yaml-config"
  max_report_age: 24
  disable_default_path_fixes: no
  require_ci_to_pass: yes
  notify:
    after_n_builds: 2
    wait_for_ci: yes

